name: Build and Push Docker Image to ACR

on:
  pull_request:
    branches:
      - main
    paths:
      - remix-weather-final/**  # Only run when app code changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TEST_ACR: testacr7wdj.azurecr.io
      PROD_ACR: prodacrji4x.azurecr.io
      IMAGE_NAME: remix-weather
      APP_DIR: remix-weather-final

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to test ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.TEST_ACR }}
          username: ${{ secrets.TEST_ACR_USERNAME }}
          password: ${{ secrets.TEST_ACR_PASSWORD }}

      - name: Build and push image to test ACR
        run: |
          docker build -t $TEST_ACR/$IMAGE_NAME:${{ github.sha }} $APP_DIR
          docker push $TEST_ACR/$IMAGE_NAME:${{ github.sha }}

      - name: Log in to prod ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.PROD_ACR }}
          username: ${{ secrets.PROD_ACR_USERNAME }}
          password: ${{ secrets.PROD_ACR_PASSWORD }}

      - name: Push image to prod ACR
        run: |
          docker tag $TEST_ACR/$IMAGE_NAME:${{ github.sha }} $PROD_ACR/$IMAGE_NAME:${{ github.sha }}
          docker push $PROD_ACR/$IMAGE_NAME:${{ github.sha }}
