name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }} # 👈 Use secret-based login now

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: iac-final-aks-rg
          cluster-name: ${{ github.event_name == 'push' && 'prod-k8s' || 'test-k8s' }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/${{ github.event_name == 'push' && 'prod-remix' || 'test-remix' }} remix=${{ github.event_name == 'push' && 'prodacrji4x.azurecr.io' || 'testacr7wdj.azurecr.io' }}/remix-weather:${{ github.sha }}
